# Generated by Django 5.1.4 on 2025-01-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
